src/Widgets/InfoBox.vala
src/Widgets/Page.vala

Previously, the displayed information about what IP address was being used on an interface came out of the DHCP config which is obviously only relevant if the interface was set up with DHCP. This resulted in no IP address information being shown for cellular modems as these are PPP connections.
Secondly, there's an important distinction between `get_iface` and `get_ip_iface`. In a lot of cases, they're the same. But often in the case of cellular modems, the `iface` is the TTY port that NetworkManager uses to control the modem and the actual network interface receiving bytes is called something else, usually `ppp0`. Therefore, we need to get that name using `get_ip_iface` instead.
For testing, this should have no effect on the normal functionality of the switchboard plug. IP addresses and …

Use more configuration agnostic ways of fetching IP info

---

src/Widgets/WifiInterface.vala

I was getting a lot of the following messages in the console when opening the network plug:
```
[FATAL 17:01:29.422303] [Gtk] gtk_stack_set_visible_child: assertion 'GTK_IS_STACK (stack)' failed
```
It looks like signals were being connected to the network interface before the stack was instantiated causing the signal handlers to try and do some stuff on a null pointer.

Initialise stack earlier to fix fatals

---

src/Plug.vala

Fixes #70 . No more fatal errors are logged when removing removable network interfaces anymore.
Before, the item was being removed from the devicelist, then we were asking the devicelist what its index was.
Switch to destroying the widget instead of removing. This ensures it gets cleaned up properly and removed from any parents automatically.

Perform better null pointer checking in devicelist

---

src/Widgets/DeviceList.vala

This activates rows when selected so that when navigating with the keyboard the selected row opens, as there is no benefit to selecting a row but not activating it.
Fixes #6

Activate row when selected

---

src/Widgets/Hotspot/HotspotDialog.vala

* Use one grid instead of nested grids and boxes
* Remove dummy label "dumb"
* Fix margins and spacing
* Wrap text instead of hardcoding a line break
* Use css style class for primary label instead of pango
* Organize

Rewrite HotSpotDialog.vala

---

src/Widgets/VPNPage.vala
src/Widgets/WifiInterface.vala

Uses Gtk.STYLE_CLASS_VIEW to style the frames rather than overriding the background colour which is deprecated.

Style frames with css

---

debian/control

Fixes #108 
We depend on this package to provide the connection editor that is launched when you click the "Settings…" button for a network or the "Edit Connections…" button

Depend on network-manager-gnome

---

src/Widgets/VPN/VPNMenuItem.vala

This caused Switchboard to crash when there were some VPN connections to create.

Fix segfault when there are VPN connections

---

src/Widgets/EtherInterface.vala

Currently we assume all wired connections are Ethernet connections. This is not always true however, as my USB tethered phone is also a wired connection. Instead, we should use the generic term "Wired" which covers the connection type without implying the use of Ethernet specifically

Show wired connections as Wired

---

src/Widgets/Page.vala
src/meson.build

Supersedes #118 
* Show an error dialog on failure to disconnect and set the correct switch state
* Remove unused signal `show_error`
*  Use `Path.build_filename` for building stats filenames
* Critical instead of warning or error

Page: Show dialog on disconnect error

---

src/Views/EthernetPage.vala
src/Views/HotspotPage.vala
src/Views/ModemPage.vala
src/Views/WifiPage.vala
src/Widgets/DeviceItem.vala
src/Widgets/Page.vala
src/Widgets/WidgetNMInterface.vala

* Use existing title property for setting page titles and reading them in the sidebar
* Set title to "Unknown Device" in Page whenever title is null. Preserves functionality

WidgetNMInterface: remove display_title property

---

src/Views/VPNPage.vala

* make sure we always throw an error dialog about failed `nm-connection-editor` launches
* Remove handling of null selected row in `nm-connection-editor` calls since we set buttons insensitive when `row_selected` returns a `null` row
* Remove setting button sensitivity around `nm-connection-editor` because it doesn't work

DRY nm connection editor calls

---

src/Widgets/WifiMenuItem.vala

I guess this comes from when we were trying to use the same widgets for the indicator as the plug

WifiMenuItem: Remove menuitem class

---

src/Views/WifiPage.vala
src/Widgets/WifiMenuItem.vala

We were hardcoding a `wpa-psk` key management type, which I suspect means Switchboard wasn't able to connect to anything other than WPA[2] networks. This doesn't seem to be necessary as the auth dialog still prompts for the correct type of Wifi credentials without this.
I've added some code that in theory supports WPA-Enterprise APs that use certificates and/or usernames and passwords for auth. This is based off code in GNOME's nm-applet.
I've also updated that code that decides what string to display under each network to check `rsn_flags` as well as `wpa_flags` for the encryption type as it was just showing every network as "Encrypted" for me. Now I get the proper "WEP/WPA" disambiguation.
This will need testing to check Switchboard can still add/connect a variety of Wifi networks. I …

Better Wifi encryption type handling

---

data/io.elementary.switchboard.network.appdata.xml.in
meson.build

It's been a while, we're still compatible with 5.x, and we have a nice little fix.
https://github.com/elementary/switchboard-plug-network/compare/2.3.2...release-2.3.3

Release 2.3.3

---

src/MainView.vala
src/Widgets/DeviceList.vala
src/Widgets/Page.vala

Fixes #311
Two parts to this, the first commit fixes a crash that happens while the plug is open and you attach a new NIC that doesn't have any available connections.
The second fixes plug crashes on startup with an extra NIC plugged in. 
The backtrace for the second type of crash is just a load of GTK signal emissions about showing/mapping/realizing widgets, and I couldn't track it down to anything specific in the networking plug. But removing a bunch of these `show_all` calls from every single method ever where they're really not necessary seems to fix things.

Fix plug crashes

---

src/Utils.vala
src/meson.build

Below are the versions of libnm that Fedora uses:
- Fedora 37: 1.40.10-1
- Fedora 38: 1.42.6-1
- Fedora Rawhide: 1.43.6-1
This project could not be compiled on Fedora Rawhide.
[Before](https://github.com/meisenzahl/distro-agnostic/actions/runs/4782702651/jobs/8502288593#step:5:3609)
[After](https://github.com/meisenzahl/distro-agnostic/actions/runs/4782964418/jobs/8502760488)
@tintou I'm not sure if we need to fix the problem or if it's a bug in the bindings for Vala. What do you think?

Add support for libnm 1.43

---

src/Widgets/Footer.vala

Updated margin of the footer switch to match other plugs.
---

Update "Airplane Mode" switch margin

---

src/Views/VPNPage.vala
src/Widgets/DeviceList.vala
src/Widgets/VPN/VPNInfoDialog.vala

This MR is an up-to-date (continuously rebased) follow up of the #302 MR plus some little adjustments.
From my point of view every thing is working as expected, but I’m open to discussion :)

Support Wireguard as a VPN connection

---

src/Widgets/VPN/VPNMenuItem.vala

Fixes a bug where closing and reopening the dialog gives you a blank window

VPNMenuItem: fix empty info dialog

---

README.md
src/Widgets/VPN/VPNMenuItem.vala
src/meson.build

Fixes chat bubble status icons. These emblems are now resourced into Granite

VPNMenuItem: use emblem status icons

---

src/MainView.vala

Automatically select the first device which is in the activated state.
I typically use the wifi connection on my laptop which also has ethernet, as would most folks. 
Whenever I open the networking plug, the first device (wired) is pre-selected and I have to do an extra click to select the wifi device to view or make changes.
Now, the wifi gets pre-selected instead, when opening the plug:
If both (or neither) wired and (nor) wireless are activated, then the first (wired) is pre-selected, preserving the current (old) behaviour.
Also, while the plug is open, toggling devices (wired, wireless) updates the selected device.
edit: No longer auto switch while plug is already open.

Auto select active network

---

src/Views/WifiPage.vala
src/Widgets/WifiMenuItem.vala

make wifimenuitem responsible for showing its own buttons

WifiMenuItem: manage own button box

---

src/Views/WifiPage.vala

Reverts elementary/switchboard-plug-network#419
This ended up resulting in a bunch of duplicates because we're combining APs with different frequencies into one item

Revert "WifiPage: update listbox with list model"

---

src/Views/EthernetPage.vala
src/Widgets/Page.vala

InfoBox: remove extra margins and align

---

data/network.metainfo.xml.in
src/MainView.vala
src/rfkill.vala

Fixes #346 
Fixes #360
Adds a proper airplane mode function, the same as in https://github.com/elementary/wingpanel-indicator-network/blob/master/src/rfkill.vala#L83
This turns of cellular and wireless radios, but not bluetooth or ethernet. Remove the "Airplane Mode" placeholder since this no longer blocks all of networking and the description here no longer applies

RKFill: add airplane mode property
