elementary/switchboard-plug-network

- src/common/Widgets/WifiMenuItem.vala
This matches the behaviour of https://github.com/elementary/wingpanel-indicator-network/pull/34 extending tooltips about the security of the network over the whole WifiMenuItem and showing an insecure icon for insecure networks and no icon for secure networks.
Fixes #48
> Display insecure icon for insecure networks

- src/Plug.vala
- src/Utils.vala
- src/Widgets/Device/DeviceItem.vala
- src/Widgets/DeviceList.vala
- src/Widgets/EtherInterface.vala
- src/Widgets/Hotspot/HotspotDialog.vala
- src/Widgets/InfoBox.vala
- src/Widgets/ModemInterface.vala
- src/Widgets/Page.vala
- src/Widgets/Proxy/ProxyExceptionsPage.vala
- src/Widgets/SettingsButton.vala
- src/Widgets/VPNInfoBox.vala
- src/Widgets/VPNPage.vala
- src/Widgets/WifiInterface.vala
- src/common/Widgets/AbstractModemInterface.vala
- src/common/Widgets/AbstractWifiInterface.vala
- src/common/Widgets/NMVisualizer.vala
- src/common/Widgets/VPNMenuItem.vala
- src/common/Widgets/WidgetNMInterface.vala
- src/common/Widgets/WifiMenuItem.vala
> Cleanup whitespace

- src/Widgets/WifiMenuItem.vala
spaces and brackets and things
> WifiMenuItem: Small code style cleanups

- src/Widgets/InfoBox.vala
> Fix subnet mask calculation

- src/Widgets/Proxy/ProxyConfigurationPage.vala
> ProxyConfigurationPage: Use GraniteMessageDialog for reset dialog

- src/Widgets/DeviceItem.vala
- src/Widgets/InfoBox.vala
> DeviceItem: Remove unused methods, organize

- src/Views/VPNPage.vala
Best viewed with "Hide Whitespace Changes"
> VPNPage: inline and explicit namespacing

- src/Widgets/WidgetNMInterface.vala
> WidgetNMInterface: remove update

- src/Widgets/NMVisualizer.vala
- src/Widgets/WidgetNMInterface.vala
Seems to be the only place this comparison is used
> NMVisualizer: compare device property directly

- src/Plug.vala
* Get rid of `connect_signals` method
* Reduce variable scope
* Organize creation of containers with their packing
> Plug: Organize mainbox

- po/POTFILES
- src/MainView.vala
- src/Plug.vala
- src/meson.build
> Move MainView to its own class

- src/Views/HotspotPage.vala
* Organize container creation with packing
* Reduce variable scope
> HotspotPage: clean up UI construction

- src/Views/VPNPage.vala
- src/Widgets/VPN/VPNMenuItem.vala
Just the row activation part from #210
> Activate row on keypress, doubleclick

- src/Widgets/WifiMenuItem.vala
* Public properties up top
* `private set` where appropriate
* `private` where appropriate
> WifiMenuItem: Clean up properties

- src/Views/WifiPage.vala
- src/Widgets/WifiMenuItem.vala
Progress toward #213 
* Always show icons
* 32px color icons
* Explicit connect button on the right
> WifiMenuItem: First steps toward redesign

- src/Utils.vala
- src/Views/WifiPage.vala
- src/Widgets/DeviceItem.vala
These are never actually used for anything
> Utils: Remove unused Wifi states

- src/Widgets/SettingsButton.vala
Remove dead constructors and use GObject style
> SettingsButton: GObjet-style and remove dead code

- src/MainView.vala
- src/Utils.vala
- src/Views/EthernetPage.vala
- src/Views/HotspotPage.vala
- src/Views/ModemPage.vala
- src/Views/VPNPage.vala
- src/Views/WifiPage.vala
- src/Widgets/DeviceItem.vala
- src/Widgets/VPN/VPNMenuItem.vala
- src/Widgets/WifiMenuItem.vala
It doesn't really seem like there's a good reason for these to be differentiated
> Utils: Combine like states

- src/Widgets/SettingsButton.vala
Fixes regression with the "Edit Connections…" button in wifi settings
> SettingsButton: Fix missing constructor

- src/Views/VPNPage.vala
> Switch to actionbar instead of toolbar

- src/Views/WifiPage.vala
Best viewed with whitespace changes off as there aren't actually many changes here.
I've just inverted the first two if statements and made them return early instead of having loads of nested if statements.
Then I've removed the call `add_seen_bssid` on a newly constructed `SettingsWireless` object as it [apparently doesn't do anything](https://valadoc.org/libnm/NM.SettingWireless.add_seen_bssid.html) and probably never did anything anyway, since that object is never used again.
The only things that need testing for regressions here is connecting to WiFi networks, though I anticipate no regressions.
> WifiPage: Code simplifications

- src/Views/EthernetPage.vala
> Display message unplugged cable 

- src/Views/HotspotPage.vala
> HotspotPage: Fix Syntax 

- src/Utils.vala
> Utils: Fix misspelled addresses

- po/zh_CN.po
- src/Views/EthernetPage.vala
- src/Widgets/Page.vala
to resolve  "Network settings panel keeps reconnecting wired network #326 "
> fix reconnecting while set switchbutton to unactive

- data/io.elementary.switchboard.network.appdata.xml.in
- meson.build
Fixes an annoyance with wired connections
> Release 2.4.2

- src/Views/WifiPage.vala
- src/Widgets/WifiMenuItem.vala
- src/meson.build
Addresses https://github.com/elementary/wingpanel-indicator-network/issues/247
> Add WPA3 connection label if available

- .github/workflows/main.yml
- src/Views/WifiPage.vala
- src/Widgets/WifiMenuItem.vala
- src/meson.build
This OWE (opportunistic wireless encryption) passwordless mode is available with at least the 6 Ghz WiFi 6E band.
This PR goes with https://github.com/elementary/wingpanel-indicator-network/pull/254
> Support OWE (opportunistic wireless encryption) passwordless mode

- src/MainView.vala
* Can't subclass paned
* Code style
* Explicit expands
* Use child property
* Remove single line functions
> MainView: Gtk4 prep and cleanup

- src/Widgets/Proxy/ProxyExceptionsPage.vala
Review with hide whitespace changes
* New copyright header
* Inline namespace
* don't use `pack_*` in box
* Use Granite HeaderLabel
* Code style
* Child property
* set tooltip text on image button
> ProxyExceptionsPage: GTK4 prep

- src/Widgets/Proxy/ProxyConfigurationPage.vala
This is a standardised protocol name that is always capitalised.
> Socks -> SOCKS

- meson.build
This fixes the plug is always shown in English nevertheless of your system language.
> l10n: Correct GETTEXT_PACKAGE

- src/MainView.vala
- src/Utils.vala
- src/Views/HotspotPage.vala
- src/Views/ProxyPage.vala
- src/Views/VPNPage.vala
- src/Widgets/DeviceItem.vala
- src/Widgets/Page.vala
Pre-req for #397, pages need to set their own status label and type
> Pages set status

- data/network.metainfo.xml.in
- src/Views/WifiPage.vala
- src/Widgets/Page.vala
> WifiPage: show SSID in sidebar when connected

- src/MainView.vala
Stores the sidebar position configured by the user.
> Store Sidebar Position

- src/Widgets/InfoBox.vala
Inspired from network-manager-applet:
https://gitlab.gnome.org/GNOME/network-manager-applet/-/blob/a1675383bdfb2df4aea191101ad9bb0f93a6d161/src/connection-editor/nm-connection-editor.c?page=2#L1216
> Fix writing changes to the metered settings

- data/network.metainfo.xml.in
- src/Widgets/InfoBox.vala
> InfoBox: add auto connect switch
